@extends('layouts.app')

@section('styles')
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet">
@endsection

@section('content')
<div id="page-wrapper">

    <!-- Header -->
    <header id="header">
        <h1><a href="#">Tombo Fans</a></h1>
    </header>

    <!-- Main -->
    <article id="main">

        <section class="wrapper style1">
            <div class="inner">

                <h1>AVISO DE PRIVACIDAD</h1>
                <p>A efectos de garantizar la privacidad y el derecho a la autodeterminación informativa de las personas, de conformidad con lo dispuesto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (la “Ley”), se le informa que Proyectos IN7, S.A. de C.V. (“Proyectos”), con domicilio en Gabino Barreda 103, Colonia San Rafael, Delegación Cuauhtémoc, Código Postal 06470, México, Distrito Federal, es responsable del tratamiento legítimo, controlado e informado de sus datos personales. En términos de la Ley, al proporcionar sus datos personales a Proyectos, a excepción de que manifieste lo contrario, usted consiente tácitamente el tratamiento de los mismos de conformidad con lo establecido en este Aviso de Privacidad. Sus datos personales podrán ser tratados sin su consentimiento en los siguientes casos: (i) cuando esté previsto en una ley; (ii) los datos figuren en fuentes de acceso público; (iii) los datos personales se sometan a un procedimiento previo de disociación; (iv) tenga el propósito de cumplir obligaciones derivadas de una relación jurídica entre el titular y el responsable; (v) exista una situación de emergencia que potencialmente pueda dañar a un individuo en su persona o en sus bienes; (vi) sean indispensables para la atención médica, la prevención, diagnóstico, la prestación de asistencia sanitaria, tratamientos médicos o la gestión de servicios sanitarios, mientras el titular no esté en condiciones de otorgar el consentimiento, en los términos que establecen las leyes y disposiciones jurídicas aplicables, y que dicho tratamiento de datos se realice por una persona sujeta al secreto profesional u obligación equivalente; o (vii) se dicte resolución de autoridad competente. En cumplimiento a lo dispuesto en los artículos 15, 16 y demás aplicables de la Ley, Proyectos pone a su disposición el presente Aviso de Privacidad, el cual estará disponible en nuestra página de internet www.tombofans.com (el “Portal”).</p>

                <p>Datos Personales. Proyectos recaba datos personales de sus usuarios incluyendo, de manera enunciativa y no limitativa, los siguientes: nombre completo, teléfonos de contacto, código postal, ciudad y dirección de correo electrónico.</p>
                <p>Dichos datos personales pueden ser obtenidos directamente de usted, ya sea personalmente o a través de cualquier medio electrónico, óptico, sonoro, visual o a través de cualquier otra tecnología, así como a través de terceros y de otras fuentes permitidas por las disposiciones legales aplicables, o bien, generados con motivo de los servicios financieros solicitados o contratados por usted con Proyectos. Proyectos cuenta con las medidas de seguridad, administrativas, técnicas y físicas necesarias para salvaguardar la privacidad y confidencialidad de sus datos personales, así como para cumplir con los principios de protección de datos personales previstos en la Ley.</p>

                <p>Finalidad del tratamiento de los Datos Personales. El tratamiento de los datos personales recabados por Proyectos será el que resulte necesario, adecuado y relevante para el cumplimiento de las siguientes finalidades principales: (i) la realización de todas y cada una de las actividades y la prestación de los servicios que, conforme a las disposiciones legales aplicables, Proyectos y sus subsidiarias o afiliadas pueden llevar a cabo, según los mismos sean contratados y solicitados por los usuarios y participantes del Portal; (ii) el cumplimiento de las disposiciones legales aplicables y de las obligaciones contraídas con nuestros usuarios; (iii) informar sobre nuevos productos o servicios o cambios en los mismos; (iv) la promoción de nuestros productos y servicios, así como las promociones que realicen los usuarios del Portal con relación a sus productos o servicios a los participantes del Portal; (v) la evaluación de la calidad de nuestros servicios, incluyendo la realización de encuestas, así como la creación e implementación de procesos analíticos y estadísticos necesarios o convenientes para dichos efectos; (vi) la atención de requerimientos de cualquier autoridad competente; (vii) la realización de consultas, investigaciones y revisiones en relación con cualquier queja o reclamación; y las siguientes finalidades secundarias: (viii) la realización de cualquier actividad, auxiliar, compatible o análoga a las finalidades anteriores o servicio complementario, sin que para ello se requiera obtener nuevamente su consentimiento.</p>
                <p>Transferencia de Datos Personales. A efecto de estar en posibilidad de dar cumplimiento a las finalidades previstas en este Aviso de Privacidad y para facilitar el cumplimiento de obligaciones legales de cualquier naturaleza de nuestros usuarios con respecto a sus promociones, se podrá efectuar la transferencia de ciertos datos personales de nuestros usuarios a favor de terceros, comprometiéndose en todo caso Proyectos a velar por el cumplimiento de los principios de protección de datos personales establecidos en la Ley y a tomar las medidas necesarias y suficientes para garantizar que tanto la Ley como este Aviso de Privacidad sean respetados en todo momento por el o los terceros a los que Proyectos transfiera los datos personales. En este sentido, Proyectos podrá realizar la transferencia de sus datos personales, entre otros, a sus empresas subsidiarias y afiliadas, autoridades, y a terceros prestadores y prestatarios de los servicios necesarios para su debida operación, para el cumplimiento de las finalidades previstas en el presente Aviso de Privacidad y para facilitar el cumplimiento de obligaciones legales y comerciales de cualquier naturaleza de sus usuarios y participantes del Portal.</p>

                <p>Proyectos no recaba, y en consecuencia, no transfiere datos personales sensibles de sus clientes.</p>

                <p>Le informamos que en la página de internet www.tombofans.com, se utilizan cookies, web beacons y otras tecnologías a través de las cuales es posible monitorear su comportamiento como usuario del Portal, lo anterior con la finalidad de brindarle un mejor servicio y experiencia de usuario al navegar en la página de internet, así como ofrecerle nuevos productos y servicios basados en sus preferencias.</p>
                <p>Los datos obtenidos con estas tecnologías de rastreo son los siguientes: horario de navegación, tiempo de navegación en el Portal, secciones consultadas, y páginas de internet accedidas previas a la página de internet www.tombofans.com.</p>
                <p>Asimismo, le informamos que los datos que se obtienen a través de estas tecnologías son compartidos con las empresas subsidiarias y afiliadas de Proyectos, y a terceros prestadores y prestatarios de los servicios necesarios para su debida operación, para el cumplimiento de las finalidades previstas en el presente Aviso de Privacidad y para facilitar el cumplimiento de obligaciones legales y comerciales de cualquier naturaleza de sus usuarios y participantes con respecto al Portal.</p>
                <p>Podrá deshabilitar el uso de cookies y otras tecnologías de acuerdo a las características del navegador de internet que utilice.</p>
                <p>Acepta también que sus datos y los de su dispositivo serán utilizados por Proyectos, en apego al presente Aviso de Privacidad para operar desde la página de internet y aplicaciones móviles.</p>
                <p>Para todos los efectos legales, salvo que usted manifieste su oposición, se entenderá que otorga su consentimiento a Proyectos para transferir a terceros sus datos personales, siempre que ello sea necesario para el cumplimiento de las finalidades establecidas en el presente Aviso de Privacidad. Lo anterior, en el entendido que el tercero receptor asumirá las mismas responsabilidades y/u obligaciones de Proyectos derivadas del presente Aviso de Privacidad, debiendo respetar el mismo en todo momento. No obstante lo anterior, Proyectos podrá llevar a cabo la transferencia de sus datos personales sin su consentimiento en los siguientes casos: (i) cuando la transferencia esté prevista en una ley o tratado en los que México sea parte; (ii) cuando la transferencia sea necesaria para la prevención o el diagnóstico médico, la prestación de asistencia sanitaria, tratamiento médico o la gestión de servicios sanitarios; (iii) cuando la transferencia sea efectuada a sociedades controladoras, subsidiarias o afiliadas bajo el control común del responsable, o a una sociedad matriz o a cualquier sociedad del mismo grupo del responsable que opere bajo los mismos procesos y políticas internas; (iv) cuando la transferencia sea necesaria por virtud de un acuerdo celebrado o por celebrar en interés del titular, por el responsable y un tercero; (v) cuando la transferencia sea necesaria o legalmente exigida para la salvaguarda de un interés público, o para la procuración o administración de justicia; (vi) cuando la transferencia sea precisa para el reconocimiento, ejercicio o defensa de un derecho en un proceso judicial, y (vii) cuando la transferencia sea precisa para el mantenimiento o cumplimiento de una relación jurídica entre el responsable y el titular.</p>

                <p>Medios para  Ejercer los Derechos de Acceso, Rectificación,  Cancelación  y  Oposición  (los “Derechos ARCO”). De conformidad con lo dispuesto en la Ley, a partir del 6 de enero de 2012, usted tendrá el derecho, en todo momento, de acceder a sus datos personales en poder de Proyectos; rectificarlos en caso de que éstos sean inexactos o estén incompletos; instruirnos a cancelarlos cuando considere que son excesivos o innecesarios para las finalidades que justificaron su obtención o haya finalizado la relación comercial con Proyectos; así como a oponerse por causa legítima al tratamiento de sus datos personales. A efecto de ejercer los Derechos ARCO antes referidos, se deberá enviar la solicitud respectiva a nuestra dirección de correo electrónico hola@tombofans.com. Para mayor información, favor de comunicarse al teléfono (55) 5592 6409. La solicitud deberá contener y acompañarse de lo siguiente: (i) su nombre y domicilio o cualquier otro medio para comunicarle nuestra respuesta; (ii) los documentos que acrediten su identidad y/o la de su representante legal; (iii) la descripción clara y precisa de los datos personales respecto de los cuales se busca ejercer alguno de los derechos mencionados; (iv) cualquier otro documento o elemento que facilite la localización de sus datos personales y; (v) tratándose de solicitudes de rectificación, deberá indicar además las modificaciones a realizarse y aportar la documentación que sustente su petición, en caso de que ésta sea procedente.</p>
                <p>Limitación del Uso y Divulgación de los Datos Personales. En adición a los derechos antes mencionados, usted tendrá, en todo momento, el derecho de limitar el uso o divulgación de sus datos personales, así como el derecho de dejar de recibir mensajes promocionales o publicidad. A efecto de ejercer dicho derecho, se deberá enviar la solicitud respectiva a la dirección de correo electrónico y con los requisitos señalados para el ejercicio de los Derechos ARCO, cuando sean aplicables.</p>
                <p>Revocación del Consentimiento para el Tratamiento de Datos Personales. Asimismo, tendrá en todo momento el derecho de revocar el consentimiento otorgado a Proyectos para el tratamiento de sus datos personales en términos de lo establecido en este Aviso de Privacidad, sin que se le atribuyan efectos retroactivos a la revocación.</p>

                <p>A efecto de ejercer dicho derecho, se deberá enviar la solicitud respectiva a nuestra Unidad Especializada de Atención a Usuarios a la dirección de correo electrónico señalada anteriormente y con los requisitos señalados para el ejercicio de los Derechos ARCO, cuando sean aplicables.</p>
                <p>Modificaciones al Aviso de Privacidad. Proyectos se reserva el derecho de efectuar, en cualquier momento, modificaciones o actualizaciones a este Aviso de Privacidad ya sea como consecuencia de reformas legislativas, políticas internas, nuevos requerimientos para la prestación u ofrecimiento de nuestros servicios y/o productos, prácticas del mercado u otros.</p>

                <p>Los cambios o modificaciones en los siguientes rubros serán dados a conocer a los clientes a través de la publicación en la página de internet www.tombofans.com en los siguientes casos:</p>
                <p>a) Cambie la identidad de Proyectos.</p>
                <p>b) Proyectos requiera recabar datos personales sensibles adicionales a aquéllos informados en el Aviso de Privacidad original, cuando los mismos no se obtengan de manera personal o directa y se requiera su consentimiento.</p>
                <p>c) Cambien las finalidades que dieron origen o sean necesarias para la relación comercial entre Proyectos y usted; o bien, se incorporen nuevas que requieran de su consentimiento.</p>
                <p>d) Se modifiquen las condiciones de las transferencias o se vayan a realizar transferencias no previstas inicialmente, y sea necesario su consentimiento.</p>

                <p>Dichas modificaciones se tendrán por aceptadas en caso de que usted no exprese su inconformidad con las mismas dentro de un plazo de 3 (tres) días contados a partir de que las mismas se hayan efectuado.</p>
                <p>Las modificaciones o actualizaciones serán incorporadas al presente Aviso de Privacidad y estarán disponibles en nuestra página de internet, o bien se le harán llegar al último correo electrónico que nos haya proporcionado.</p>

                <p>Quejas y Denuncias. En caso de que usted considere que el derecho a la protección de sus datos personales ha sido vulnerado por alguna conducta de nuestros empleados o por la actuación de Proyectos y, por tanto, presuma que existe alguna violación a las disposiciones previstas en la Ley, podrá interponer la queja correspondiente ante el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (“INAI”). Para mayor información visite la página de internet www.inai.org.mx.</p>
                <p>De conformidad con lo previsto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, reconozco que he leído y entiendo los alcances del Aviso de Privacidad de Proyectos IN7, S.A. de C.V. y autorizo de forma expresa a Proyectos IN7, S.A. de C.V. a recabar, tratar y transferir mis datos personales para los fines establecidos en y de conformidad con lo previsto en el Aviso de Privacidad, según el mismo sea modificado de tiempo en tiempo.</p>
                <p>Fecha última de actualización 01 de diciembre de 2016.</p>
            </div>
        </section>
    </article>

    <!-- Footer -->
    @include('includes.footer')
</div>
@endsection
