@extends('layouts.app')

@section('styles')
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet">
@endsection

@section('content')
<div id="page-wrapper">
    <header id="header">
        <h1><a href="#">Tombo Fans</a></h1>
    </header>

    <article id="main">

        <section class="wrapper style1">
            <div class="inner">

                <h2>TÉRMINOS Y CONDICIONES</h2>

                <p>Proyectos IN7, S.A. de C.V., (“Proyectos”) requiere que todos los Usuarios que utilicen o accedan al portal Tombofans.com (en adelante, el “TomboFans”), se adhieran a los siguientes términos y condiciones de uso (los “Términos y Condiciones”).</p>
                <p>Por consiguiente, debes leer cuidadosamente los siguientes Términos y Condiciones, ya que por el simple hecho de acceder o utilizar Tombofans, se entenderá que el Usuario ha leído, acepta y está de acuerdo en obligarse de conformidad con los presentes Términos y Condiciones, según los mismos sean modificados por Proyectos de tiempo en tiempo.<p>
                <p>Estos Términos y Condiciones, y sus modificaciones periódicas, constituyen las reglas generales para uso de TomboFans.</p>
                <p>En caso de que no estés de acuerdo con los presentes Términos y Condiciones, deberás abstenerte de utilizar TomboFans.</p>

                <h2>1.	USO Y RESTRICCIONES.</h2>
                <p>Por el simple uso de TomboFans, el Usuario expresa su consentimiento pleno y adhesión sin reservas a los presentes Términos y Condiciones.</p>
                <p>Mediante el uso de TomboFans el Usuario podrá accesar a, y/o utilizar, los diversos servicios y contenidos (en lo sucesivo, los "Servicios y/o Contenidos"), puestos a disposición de los Usuarios, y/o sus subsidiarias y afiliadas, y/o por terceros proveedores de servicios que, de tiempo en tiempo, puedan ofrecer sus servicios a través de TomboFans (cada uno, un “Prestador de Servicios”).</p>
                <p>El aprovechamiento de los Servicios y Contenidos de TomboFans es exclusiva responsabilidad del Usuario, quien en todo momento deberá utilizarlos de conformidad con las funcionalidades que se ofrecen y permiten en el propio Tombofans y con los usos autorizados en los presentes Términos y Condiciones. En este sentido, el Usuario se obliga a utilizar los Servicios y/o Contenidos de TomboFans, de modo tal que no atenten contra las normas de uso, normas de privacidad y convivencia en Internet, las leyes de los Estados Unidos Mexicanos y/o la legislación vigente en el país en que el Usuario se encuentre al usarlos, las buenas costumbres, la dignidad de la persona y los derechos de terceros.</p>
                <p>TomboFans se ofrece para ser utilizado de manera personal, privada y particular por el Usuario, por lo que no podrá de manera alguna, ser copiado, modificado, dado en licencia, publicado, reproducido o utilizado con fines comerciales o sin fines lucro. Queda expresamente prohibido el uso o aplicación de cualesquiera recursos técnicos, lógicos o tecnológicos por virtud de los cuales los Usuarios puedan beneficiarse, directa o indirectamente, con o sin lucro, de la explotación no autorizada de los Servicios y/o Contenidos de TomboFans.</p>
                <p>Proyectos tendrá, en todo momento, el derecho de negar, restringir, suspender, cancelar o condicionar al Usuario el acceso al y/o uso de TomboFans, ya sea total o parcialmente, de manera temporal o definitiva y sin necesidad de previo aviso, si el Usuario quebranta cualquiera de las estipulaciones de los presentes Términos y Condiciones o del Contrato de Servicios, si comete cualquier acto contrario a las leyes aplicables vigentes, si no pudiera verificarse su identidad, si cualquier información proporcionada por el mismo fuere falsa o por cualquier otra causa, a entera discreción de y sin responsabilidad para Proyectos. Asimismo, Proyectos tendrá el derecho de modificar los Servicios y/o Contenidos de TomboFans, sin que lo anterior se considere un incumplimiento ni de Proyectos, ni de sus subsidiarias o afiliadas, ni del Prestador de Servicios correspondiente.</p>
                <p>El Usuario reconoce y acepta que no todos los Servicios y/o Contenidos están disponibles en todas las áreas geográficas y que algunos Servicios y/o Contenidos pueden ser utilizados solamente con posterioridad a la solicitud que realice el Usuario, la correspondiente inscripción, registro previo o cualquier otro requisito que establezca Proyectos y mediante el pago de una comisión o cuota, según sea el caso, de conformidad con el Contrato de Servicios.</p>

                <h2>2.	CALIDAD DE LOS SERVICIOS Y   CONTENIDOS</h2>
                <p>La información contenida en TomboFans ha sido incluida y/o elaborada por Proyectos con la finalidad de proporcionar información general a los Usuarios. Los procedimientos, normas de privacidad, opiniones, estimaciones y proyecciones que, en su caso, sean incluidas en TomboFans, pueden modificarse de acuerdo a las condiciones tecnológicas, comerciales, regulatorias y por parte de terceros que impliquen modificaciones en TomboFans.com. Proyectos se reserva el derecho de actualizar, cambiar, modificar o eliminar la información incluida en TomboFans, en cualquier momento y sin previo aviso.</p>
                <p>La información que Proyectos pone a disposición de los Usuarios a través de TomboFans, es  de naturaleza general y ha sido obtenida de fuentes que se consideran fidedignas; sin embargo, Proyectos no garantiza su veracidad. La intención de proporcionar esta información no implica la emisión de juicios de valor por parte de Proyectos, sus directivos, funcionarios, ejecutivos, empleados, apoderados, asesores o terceros; por lo tanto, la información, opiniones, estimaciones, proyecciones y casos de éxito expresadas en TomboFans, son meramente enunciativas y deberán ser consideradas por el Usuario exclusivamente para efectos informativos, en virtud de no llevar implícita ninguna recomendación que obligue al Usuario y a Proyectos para la celebración de contrato, por lo que su utilización será bajo la más estricta responsabilidad exclusiva del Usuario.</p>
                <p>Ni Proyectos, sus subsidiarias y/o afiliadas, ni sus proveedores o socios comerciales serán responsables de cualquier daño o perjuicio que sufra el Usuario a consecuencia de demoras, inexactitudes, errores u omisiones de cualquier índole, cambios o mejoras que se realicen periódicamente a los Servicios y/o Contenidos, o de los resultados obtenidos por la utilización de la información contenida en TomboFans.</p>
                <p>Proyectos no garantiza ni respalda la veracidad, precisión o confiabilidad de cualquier información, contenido o publicidad contenidos en, distribuidos a través de, enlazados, grabados o accesados a través de TomboFans, ni la calidad de cualquier producto, información u otros materiales exhibidos, adquiridos u obtenidos por el Usuario como resultado de cualquier publicidad o cualquier información u oferta contenidos en, o que tengan relación con los Servicios y/o Contenidos en TomboFans.</p>

                <h2>3.	INSTRUCCIONES Y PARTICIPACIONES</h2>
                <p>Las instrucciones y participaciones  que puedan realizarse a través de TomboFans así como la forma de realizar y organizar cualquier tipo de promoción para cualquier participante, se regirán por los términos y condiciones establecidos en el Contrato de Servicios.</p>
                <p>Proyectos no asume ninguna obligación de las promociones, descuentos, regalos o dádivas que los Usuarios promuevan a los participantes de TomboFans, ni de ser responsable de las pérdidas que el Usuario pueda sufrir como consecuencia de cualquier tipo de falla.</p>

                <h2>4.	DISPONIBILIDAD DE TOMOFANS</h2>
                <p>Proyectos no garantiza la disponibilidad y continuidad de la operación de TomboFans y de los Servicios y/o Contenidos, ni la utilidad de TomboFans o los Servicios y/o Contenidos en relación con ninguna actividad específica. El Usuario libera a Proyectos de cualquier responsabilidad que, por cualquier daño o perjuicio de cualquier naturaleza, pudiera surgir debido a la falta de disponibilidad o continuidad de operación de TomboFans y/o de los Servicios y/o Contenidos.</p>
                <p>En este sentido, el Usuario acepta expresamente que Proyectos no será responsable por cualquier daño, perjuicio o pérdida que surja en relación con fallas en el rendimiento, error, omisión, interrupción, defecto, demora en la operación o transmisión de TomboFans, o en la Internet, ni por cualquier virus de computadora o falla de sistema o línea que pudiera infectar o afectar el equipo del Usuario como consecuencia del acceso o uso de TomboFans o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo; así como tampoco Proyectos será responsable de los daños o perjuicios que se ocasionen como consecuencia de deficiencias, desperfectos, fallas u otros problemas que se originen por la instalación, adecuación y conexión de los sistemas del Usuario y de cualquier participante, ni de los daños y perjuicios que se le pudieran causar si, por caso fortuito, fuerza mayor o por cualquier otro acontecimiento o circunstancia inevitable, más allá del control razonable de Proyectos, el Usuario no pudiera hacer uso o uso oportuno de TomboFans.</p>

                <h2>5.	BIENES Y SERVICIOS DE TERCEROS ENLAZADOS</h2>
                <p>Proyectos podrá, de tiempo en tiempo, desde Tombofans ofrecer, mediante enlaces, iconos, banners u otros, ligas a otros sitios o páginas Web de diversos Prestadores de Servicios independientes que pudieran ser del interés del Usuario y cualquier participante; lo anterior en el entendido que los servicios y contenidos de los sitios enlazados, han sido desarrollados y son mantenidos independientemente por dichos Prestadores de Servicios, por lo que no podrá considerarse que existe algún tipo de asociación o relación entre Proyectos y dichos terceros. En este sentido, el Usuario reconoce y acepta que Proyectos no será responsable por los cambios en los enlaces o sus direcciones, así como tampoco por la actualización, calidad, veracidad, integridad y consistencia de la información o la disponibilidad y funcionamiento de dichos sitios o respecto de cualquier acto, omisión o garantía de cualquier tipo relacionada con los mismos.</p>
                <p>Los productos y/o servicios de terceros que se comercialicen dentro de TomboFans y/o en los sitios de los Prestadores de Servicios enlazados, serán suministrados por comerciantes independientes a Proyectos, por lo que Proyectos no tendrá obligación o responsabilidad alguna respecto a la entrega o no de los respectivos servicios o contenidos de tales Prestadores de Servicios o de la precisión, totalidad, calidad o puntualidad de los mismos.</p>
                <p>Respecto de los servicios y contenidos que presten los Prestadores de Servicios dentro o mediante enlaces a TomboFans, el Usuario reconoce y acepta que la función de Proyectos se limita exclusivamente, y para conveniencia del Usuario, a: (i) informar al Usuario la existencia de dichos servicios; y (ii) a proporcionar un medio para poner en contacto al Usuario con los Prestadores de Servicios.</p>
                <p>Proyectos no es, ni podrá ser considerado como proveedor de los bienes y/o servicios que se ofrecen en las páginas y/o sitios de los Prestadores de Servicios. La inclusión de dichas páginas y/o enlaces no implica la aprobación, respaldo, patrocinio, recomendación o garantía, por parte de Proyectos, de los servicios y bienes que se comercializan en los mismos ni del contenido de dichas páginas. No existe ningún tipo de relación laboral, asociación o sociedad, entre Proyectos y dichos Prestadores de Servicios. Toda asesoría, consejo, declaración, información y contenido de las páginas de Prestadores de Servicios enlazadas o dentro de Tombofans representan las opiniones y juicios de dicho Prestador de Servicios, consecuentemente, Proyectos no será responsable de ningún daño o perjuicio que sufra el Usuario a consecuencia de los mismos, incluyendo, de manera enunciativa mas no limitativa, los daños causados por pérdidas económicas y pérdidas de datos o programas;  no garantiza ni asume responsabilidad alguna por los daños y perjuicios de cualquier clase que pudieran causarse por el funcionamiento, disponibilidad, accesibilidad, continuidad, mantenimiento de los servicios, información, datos, archivos, obligaciones, ofertas, productos y cualquier clase de material existente en los sitios enlazados.</p>
                <p>Por consiguiente el Usuario, debe extremar prudencia en la valoración y utilización de los servicios, información, datos, privacidad, archivos, productos y cualquier clase de material de terceros existente en los sitios de los Prestadores de Servicios enlazados. El acceso a cualquier sitio enlazado a TomboFans es bajo el propio riesgo y responsabilidad del <Usuario class="</p>"></Usuario>
                <p>Por lo anterior, el Usuario entiende que la relación cliente - proveedor o con sitios de terceros Prestadores de Servicios será exclusivamente entre estos y el Usuario, y bajo ninguna circunstancia con Proyectos, por lo que no contará con ninguna acción legal de reclamación, queja o cualquier otra, en contra de Proyectos, en caso de incumplimiento, por parte del Prestador de Servicios o de cualquier sitio propiedad de terceros.</p>

                <h2>6.	CLAVES DE ACCESO Y NÚMEROS CONFIDENCIALES</h2>
                <p>Las claves de usuario, números de identificación personal y, en su caso, las claves para acceder a Tombofans (las “Claves de Acceso”) que Proyectos asigne al Usuario para acceder y utilizar a los Servicios y/o Contenidos de TomboFans, son personales, confidenciales e intransferibles por lo que, en todo momento, la custodia y el uso de dichas Claves de Acceso, serán de la exclusiva responsabilidad del Usuario en términos de lo establecido en el Contrato de Servicios.</p>

                <h2>7.	CONFIDENCIALIDAD</h2>
                <p>Proyectos se obliga a mantener como confidencial, la información que reciba del Usuario que tenga dicho carácter de conformidad con las disposiciones legales aplicables en los Estados Unidos Mexicanos y en términos del Aviso de Privacidad de Proyectos.</p>
                <p>El Usuario reconoce y acepta que Proyectos no será responsable de mantener con el carácter de confidencial, cualquier otra información que el Usuario libremente le proporcione, ya sea al inscribirse a Tombofans o en cualquier otro momento posterior, que sea de cualquier forma pública o que no deba considerarse como confidencial en términos de las disposiciones legales aplicables, incluyendo aquella información que el Usuario proporcione a través de comunicados, boletines, pizarras o plática en línea (chats), así como la información que obtenga Proyectos a través de las Cookies (según dicho término se define más adelante).</p>

                <h2>8.	TRATAMIENTO DE DATOS PERSONALES</h2>
                <p>Para mayor información sobre el tratamiento de los datos personales de los Usuarios de Tombofans, favor de dirigirse al Aviso de Privacidad de Proyectos disponible en www.tombofans.com.</p>

                <h2>9.	COOKIES</h2>
                <p>El Usuario que tenga acceso a TomboFans, está de acuerdo en recibir las Cookies que les transmitan los servidores de Proyectos. Una "Cookie" es un archivo de datos que se almacena en el disco duro de la computadora del Usuario cuando éste tiene acceso a TomboFans. Las Cookies pueden contener información tal como la identificación proporcionada por el Usuario o información para rastrear las páginas que el Usuario ha visitado. Una Cookie no puede leer los datos o información del disco duro del Usuario ni leer las Cookies creadas por otros sitios o páginas.</p>

                <h2>10.	PROHIBICIONES</h2>
                <p>El Usuario se compromete a no utilizar a TomboFans para la realización de actividades contrarias a la Ley, a la moral, a las buenas costumbres aceptadas o al orden público establecido, incluyendo sin limitar actividades con fines o efectos ilícitos, prohibidos o lesivos de derechos e intereses de terceros, liberando a Proyectos de cualquier responsabilidad que se pudiera derivar de todo lo anterior.</p>
                <p>Queda terminantemente prohibida la utilización de TomboFans de cualquier manera que pudiera dañar, inutilizar, sobrecargar, saturar o deteriorar cualquier equipo, sistema informático, equipo de telecomunicaciones, servidor de Proyectos, o cualquier red conectada a los servidores de Proyectos y los contenidos incorporados y/o almacenados en los mismos. Asimismo, no se podrá utilizar a TomboFans de modo que interfiera, impida o limite el normal y correcto uso y disfrute de cualquier otro Usuario o del propio  Proyectos.</p>
                <p>El Usuario reconoce que no tiene el derecho de y, por lo tanto, acepta y se obliga a no colocar hiperligas de y a TomboFans, ni a colocar o utilizar los Servicios y/o Contenidos de TomboFans en sitios o páginas propias o de terceros sin autorización previa y por escrito de Proyectos.</p>

                <h2>11.	PROPIEDAD INTELECTUAL</h2>
                <p>Los derechos de propiedad industrial o intelectual, incluyendo sin limitar las marcas, logotipos, avisos comerciales, signos distintivos, nombres comerciales, patentes, diseños industriales, diseños y dominios exhibidos en y/o que se desprendan de TomboFans y/o los Servicios y/o Contenidos, así como los derechos de uso y explotación de los mismos, incluyendo sin limitar su divulgación, publicación, reproducción, distribución y transformación, son propiedad exclusiva de Proyectos o del legítimo propietario de los mismos y están protegidos por las leyes y tratados internacionales aplicables. El Usuario no adquiere ni podrá adquirir ningún derecho de propiedad industrial o intelectual por el simple uso de los Servicios y Contenidos de TomboFans y, en ningún momento, dicho uso será considerado como una autorización ni licencia para utilizar  los Servicios y Contenidos con fines distintos a los que se contemplan en los presentes Términos y Condiciones.</p>
                <p>El Usuario acuerda que las disposiciones que se establecen en el párrafo anterior, también son aplicables a los derechos de terceros respecto de los Servicios y Contenidos de las páginas enlazadas a TomboFans.</p>

                <h2>12.	MODIFICACIONES</h2>
                <p>Al acceder a TomboFans, el Usuario entiende y acepta que Proyectos tendrá, en todo momento, el derecho de modificar los presentes Términos y Condiciones, sin previo aviso. En consecuencia, el Usuario acepta que es su obligación el revisar periódicamente estos Términos y Condiciones y leerlos cada vez que pretenda utilizar a TomboFans.</p>
                <p>Ciertos Servicios y Contenidos ofrecidos a los Usuarios en y/o a través de TomboFans, están sujetos, en su caso, a condiciones particulares propias que sustituyen, completan y/o modifican los presentes Términos y Condiciones (en lo sucesivo, las "Condiciones Particulares"). Consiguientemente, cuando sea aplicable, el Usuario deberá también leer con cuidado las correspondientes Condiciones Particulares antes de acceder a cualesquiera Servicios y/o Contenidos.</p>

                <h2>13.	LEYES APLICABLES Y JURISDICCIÓN</h2>
                <p>Para la interpretación, cumplimiento y ejecución de los presentes Términos y Condiciones, las partes están de acuerdo en que serán aplicables las leyes federales de los Estados Unidos Mexicanos y competentes los tribunales ubicados en la Ciudad de México, renunciando expresamente a cualquier otro fuero o jurisdicción que pudiera corresponderles en razón de sus domicilios presentes o futuros o por cualquier otra causa.</p>

            </div>
        </section>
    </article>

    <!-- Footer -->
    @include('includes.footer')
</div>
@endsection
